### ISSUE TITLE
Feature 1 : User can view the NBA Conferences (Western and Eastern).

### ISSUE THREAD

**Issue by jeffmjin** [jeffmjin/the-ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view both of the conferences. (This will be the main page).

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Use HTML and CSS to create the page that is similar or identical to the wireframe.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop View:
<img width="714" alt="Screen Shot 2022-11-11 at 3 37 14 PM" src="https://user-images.githubusercontent.com/110066310/201444592-19469fff-78a1-4c6a-a0cb-b0d6ed88aba7.png">
Mobile View:
<img width="185" alt="Screen Shot 2022-11-11 at 3 37 32 PM" src="https://user-images.githubusercontent.com/110066310/201444603-f1009c02-e0b7-41fa-b800-5788839a3a6c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Copy the wireframe using HTML and CSS. The images will be in a folder.
- [ ] Listen for 'clicks' on the images.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Make sure the page looks very similar in both mobile and desktop view.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
